Feature/homework 2
Lana-asv/FocusStartHomework pull request #2
Opened 2021-11-04 09:16 UTC by Lana-asv

2021-11-07 06:57 UTC, AlexRaptor requested changes

2021-11-07 06:57 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +public class ThreadSafeArray<T: Equatable> {
- [ ] вынеси коллекцию в отдельный файл

2021-11-07 06:57 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +    public func removeAtIndex(index: Int) {
- [ ] название не соответствует ТЗ

2021-11-07 06:57 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +        queue.async(flags: .barrier) {
- [ ] удаление не потоко-безопасно

2021-11-07 06:57 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +        queue.sync { result = self.array.contains(element)}
- [ ] пробел перед скобкой пропущен

2021-11-07 06:57 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +            queue.sync {
мне кажется, что для чтения это не нужно

2021-11-07 06:57 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +group.enter()
- [ ] перенеси это внутрь таски

2021-11-08 08:38 UTC, AlexRaptor commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +            queue.sync {
я ошибался :) нужно!!!

2021-11-08 11:47 UTC, Lana-asv commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +        queue.async(flags: .barrier) {
не очень разобралась с этой проблемой. добавила guard, погуляла, пишут вот что: 
The fundamental problem in this example is that any time the array is modified, it invalidates existing indices. In order to safely use an index, you must ensure that the entire "fetch an index, use the index" operation is atomic. You can't just ensure that each piece is atomic. There is no safe way to write removeAtIndex in isolation, because there is no safe way to acquire the index you pass. Between the time you fetch the index, and the time you use it, the array may have been changed in arbitrary ways.

получается, что полностью потокобезопасное удаление по индексу не реализовать?

2021-11-08 15:01 UTC, AlexRaptor requested changes
Поправь работу с группами

2021-11-09 03:58 UTC, AlexRaptor approved these changes
👍

2021-11-09 15:52 UTC, merged