Feature/homework 3
Lana-asv/FocusStartHomework pull request #3
Opened 2021-11-12 08:59 UTC by Lana-asv

2021-11-15 04:56 UTC, c0dedbear requested changes
Выглядит неплохо. Но в задании я говорил что хотел бы видеть информацию о вас самих. Стив Джобс парень хороший, но с ним увы в будущем не поработать и не пообщаться.

p.s. в настройках проекта не отключена поддержка iPad.

2021-11-15 04:56 UTC, c0dedbear commented on myCV/myCV/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
Если класс не планируется наследовать нужно ставить final.

2021-11-15 04:56 UTC, c0dedbear commented on myCV/myCV/AppDelegate.swift
> +    func application(_ application: UIApplication, didDiscardSceneSessions sceneSessions: Set<UISceneSession>) {
Не используемые методы и комментарии надо удалять.

2021-11-15 04:56 UTC, c0dedbear commented on myCV/myCV/FirstViewController.swift
> +    private lazy var imageView = UIImageView()
В свойствах неоправданный lazy var. У тебя все свойства проинициализированы сразу и настраиваются позже, достаточно let.

2021-11-15 04:56 UTC, c0dedbear commented on myCV/myCV/FirstViewController.swift
> +    override func viewDidLoad() {
не стоит делать из viewDidLoad метод где настраивается все и вся, нужно чтобы внутри этот метод выглядел как набор инструкций из приватных методов в которых настраивается ui и т.д.
Относится ко всем VC.

2021-11-15 04:56 UTC, c0dedbear commented on myCV/myCV/FirstViewController.swift
> +    func LayoutSetup() {
методы не называем с Большой буквы. Вот в didLoad должно быть примерно как внутри этого метода.
Этот метод да и остальные в этом файле следует сделать private.

2021-11-15 04:56 UTC, c0dedbear commented on myCV/myCV/SecondViewController.swift
> +    private lazy var nameLabel = UILabel()
тоже самое с lazy var

2021-11-15 04:56 UTC, c0dedbear commented on myCV/myCV/TabBarModel.swift
> +struct TabBarTitle {
Для хранения статических свойства лучше использовать enum'ы. Их нельзя создать пока ты не пропишешь init()

2021-11-15 04:56 UTC, c0dedbear commented on myCV/myCV/TabBarModel.swift
> +    static let firstVCPicture = UIImage(named: "harry-potter")
нет смысла хранить UIImage в статике, храни имена файлов, создавай UIImage по месту их использования.

2021-11-15 16:01 UTC, c0dedbear requested changes

2021-11-15 16:35 UTC, Lana-asv reviewed
обидно все final все исправила и забыла запушить((

2021-11-16 04:55 UTC, c0dedbear requested changes
унести маг цифры в enum Metrics

2021-11-16 04:55 UTC, c0dedbear commented on myCV/MyCV/FirstView.swift
> +        postLb.font = UIFont.boldSystemFont(ofSize: 24)
Размер шрифта в метрики унеси.

2021-11-16 04:55 UTC, c0dedbear commented on myCV/MyCV/FirstView.swift
> +            postView.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 10),
все значения отступов тоже в enum  с метриками, избегай магических цифр.

2021-11-16 09:31 UTC, c0dedbear approved these changes
Принято

2021-11-16 09:31 UTC, merged